name: docker_tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: build and test
      run: |
        docker build --tag whoogle-search:test .
        docker run --publish 5000:5000 --detach --name whoogle-search whoogle-search:test
        sleep 15
        docker exec whoogle-search curl -f http://localhost:5000/healthz || exit 1
