name: scan

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the container image
      run: |
        docker build --tag whoogle-search:test .
    - name: Initiate grype scan
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b .
        chmod +x ./grype
        ./grype whoogle-search:test --only-fixed
